name: fresh_bits_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  bouncing_widget: ^2.0.0
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.5
  flutter_spinkit: ^5.2.0
  sqflite: ^2.2.4+1
  path: ^1.8.2
  awesome_dialog: ^3.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/